"""baseline: existing production schema

Revision ID: 6dc6b1f7f8fb
Revises: 
Create Date: 2026-09-08 16:01:02.779993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel            # SQLModel이 str 컬럼을 AutoString으로 렌더링한다.
                           # 이 import가 없으면 생성된 리비전이 NameError로 죽는다.


# revision identifiers, used by Alembic.
revision: str = '6dc6b1f7f8fb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('main_page_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hero_subtitle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('discover_subtitle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cta_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cta_subtitle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hero_bg1_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hero_bg2_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nickname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('profile_image', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('provider', sa.Enum('LOCAL', 'GOOGLE', 'NAVER', name='loginprovider'), nullable=False),
    sa.Column('social_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('active_template', sa.Integer(), nullable=False),
    sa.Column('subscription_plan', sa.Enum('FREE', 'STANDARD', 'PREMIUM', name='subscriptionplan'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('social_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('career_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['career_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discover_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slot_order', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spotlight_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subtitle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('artist_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('genre', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t1_album_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('t1_contact_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phone1', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone2', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email1', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email2', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email3', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('instagram_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tiktok_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('youtube_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extra_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('t1_name_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('thumbnail_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('english_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tagline', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description1', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description2', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('t1_text_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t2_album_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('t2_contact_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phone1', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone2', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email1', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email2', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email3', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('instagram_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tiktok_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('youtube_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extra_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('t2_image_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t2_name_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('thumbnail_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('english_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tagline', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description1', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description2', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('activity_area', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('t2_text_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t1_image_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('album_section_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('hyperlink', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('project_title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('project_subtitle', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('album_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('composer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category_desc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['album_section_id'], ['t1_album_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t1_name_section_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_section_id', sa.Integer(), nullable=False),
    sa.Column('career_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['career_item_id'], ['career_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['name_section_id'], ['t1_name_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t1_no_image_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('album_section_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('mp3_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('project_title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('project_subtitle', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('album_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('composer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category_desc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['album_section_id'], ['t1_album_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t1_soundcloud_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('album_section_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('project_title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('project_subtitle', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('album_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('composer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category_desc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['album_section_id'], ['t1_album_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t1_text_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_section_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('detail', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['text_section_id'], ['t1_text_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t1_youtube_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('album_section_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('project_title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('project_subtitle', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('album_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('composer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category_desc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['album_section_id'], ['t1_album_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t2_image_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('album_section_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('hyperlink', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('project_title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('project_subtitle', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('album_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('composer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category_desc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['album_section_id'], ['t2_album_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t2_image_section_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_section_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['image_section_id'], ['t2_image_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t2_name_section_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_section_id', sa.Integer(), nullable=False),
    sa.Column('career_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['career_item_id'], ['career_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['name_section_id'], ['t2_name_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t2_no_image_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('album_section_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('mp3_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('project_title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('project_subtitle', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('album_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('composer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category_desc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['album_section_id'], ['t2_album_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t2_soundcloud_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('album_section_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('project_title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('project_subtitle', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('album_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('composer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category_desc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['album_section_id'], ['t2_album_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t2_text_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_section_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('detail', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['text_section_id'], ['t2_text_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t2_youtube_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('album_section_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('project_title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('project_subtitle', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('album_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('composer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category_desc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['album_section_id'], ['t2_album_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('career_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['career_item_id'], ['career_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t1_text_card_body_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_card_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['text_card_id'], ['t1_text_cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t2_text_card_body_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_card_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['text_card_id'], ['t2_text_cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t2_text_card_body_items')
    op.drop_table('t1_text_card_body_items')
    op.drop_table('user_jobs')
    op.drop_table('t2_youtube_cards')
    op.drop_table('t2_text_cards')
    op.drop_table('t2_soundcloud_cards')
    op.drop_table('t2_no_image_cards')
    op.drop_table('t2_name_section_jobs')
    op.drop_table('t2_image_section_images')
    op.drop_table('t2_image_cards')
    op.drop_table('t1_youtube_cards')
    op.drop_table('t1_text_cards')
    op.drop_table('t1_soundcloud_cards')
    op.drop_table('t1_no_image_cards')
    op.drop_table('t1_name_section_jobs')
    op.drop_table('t1_image_cards')
    op.drop_table('t2_text_sections')
    op.drop_table('t2_name_sections')
    op.drop_table('t2_image_sections')
    op.drop_table('t2_contact_sections')
    op.drop_table('t2_album_sections')
    op.drop_table('t1_text_sections')
    op.drop_table('t1_name_sections')
    op.drop_table('t1_contact_sections')
    op.drop_table('t1_album_sections')
    op.drop_table('spotlight_settings')
    op.drop_table('discover_cards')
    op.drop_table('career_items')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('main_page_content')
    op.drop_table('career_categories')
    # ⚠️ 테이블을 지워도 Postgres enum 타입은 남습니다.
    #    이걸 안 지우면 downgrade 후 다시 upgrade할 때
    #    "type \"userrole\" already exists" 로 실패합니다 —
    #    즉 이 리비전이 "되돌릴 수 없는" 것이 됩니다. 실제로 겪고 추가했습니다.
    #    타입을 쓰는 컬럼이 모두 사라진 뒤여야 하므로 반드시 테이블 삭제 다음입니다.
    for _enum in ("userrole", "loginprovider", "subscriptionplan"):
        op.execute(f"DROP TYPE IF EXISTS {_enum}")
    # ### end Alembic commands ###
